-- Commoners Deck
SMODS.Challenge {
    key = 'nothing_fancy',

    restrictions = {
        banned_tags = {
            { id = 'tag_uncommon' },
            { id = 'tag_rare' },
        },
        banned_cards = {
            -- Uncommon
            { id = 'j_stencil' },
            { id = 'j_mime' },
            { id = 'j_ceremonial' },
            { id = 'j_dusk' },
            { id = 'j_fibonacci' },
            { id = 'j_steel_joker' },
            { id = 'j_hack' },
            { id = 'j_blackboard' },
            { id = 'j_sixth_sense' },
            { id = 'j_constellation' },
            { id = 'j_hiker' },
            { id = 'j_card_sharp' },
            { id = 'j_madness' },
            { id = 'j_vampire' },
            { id = 'j_hologram' },
            { id = 'j_lucky_cat' },
            { id = 'j_bull' },
            { id = 'j_trading' },
            { id = 'j_flash' },
            { id = 'j_trousers' },
            { id = 'j_ramen' },
            { id = 'j_acrobat' },
            { id = 'j_sock_and_buskin' },
            { id = 'j_rough_gem' },
            { id = 'j_bloodstone' }, 
            { id = 'j_arrowhead' },
            { id = 'j_onyx_agate'},
            { id = 'j_ring_master' },
            { id = 'j_oops' },
            { id = 'j_idol' },
            { id = 'j_seeing_double' },
            { id = 'j_bootstraps' },
            { id = 'j_burglar' },
            { id = 'j_space' },
            { id = 'j_pareidolia' },
            { id = 'j_erosion' },
            { id = 'j_cloud_9' },
            { id = 'j_rocket' },
            { id = 'j_midas_mask' },
            { id = 'j_luchador' },
            { id = 'j_gift' },
            { id = 'j_turtle_bean' },
            { id = 'j_to_the_moon' },
            { id = 'j_stone' },
            { id = 'j_diet_cola' },
            { id = 'j_selzer' }, -- nice typo localthunk
            { id = 'j_castle' },
            { id = 'j_mr_bones' },
            { id = 'j_certificate' },
            { id = 'j_smeared' },
            { id = 'j_throwback' },
            { id = 'j_glass' },
            { id = 'j_ring_master' }, -- name wack
            { id = 'j_flower_pot' },
            { id = 'j_merry_andy' },
            { id = 'j_satellite' },
            { id = 'j_cartomancer' },
            { id = 'j_astronomer' },
            { id = 'j_matador' },
            { id = 'j_loyalty_card' },
            { id = 'j_troubadour' },
            { id = 'j_four_fingers' },
            { id = 'j_marble' },
            { id = 'j_seance' },
            { id = 'j_shortcut' },
    
            -- Rare
            { id = 'j_baron' },
            { id = 'j_obelisk' },
            { id = 'j_baseball' },
            { id = 'j_vagabond' },
            { id = 'j_ancient' },
            { id = 'j_blueprint' },
            { id = 'j_campfire' },
            { id = 'j_brainstorm' },
            { id = 'j_drivers_license' },
            { id = 'j_duo' },
            { id = 'j_trio' },
            { id = 'j_family' },
            { id = 'j_order' },
            { id = 'j_tribe' },
            { id = 'j_dna' },
            { id = 'j_stuntman' },
            { id = 'j_hit_the_road' },
            { id = 'j_invisible' },
            { id = 'j_burnt' },
            { id = 'j_wee' },

            -- Legendary
            { id = 'j_caino' }, -- nice typo localthunk
            { id = 'j_triboulet' },
            { id = 'j_yorick' },
            { id = 'j_perkeo' },
            { id = 'j_chicot' },

            -- Modded
            { id = 'j_bccp_bubble' },
            { id = 'j_bccp_coven' },
            { id = 'j_bccp_exoplanet' },
            { id = 'j_bccp_fast_fashion' },
            { id = 'j_bccp_fax_machine' },
            { id = 'j_bccp_knight' },
            { id = 'j_bccp_lighter' },
            { id = 'j_bccp_mining_operation' },
            { id = 'j_bccp_seasonal_joker' },
            { id = 'j_bccp_the_woker' },
            { id = 'j_bccp_two_birds_one_stone' },
            { id = 'j_bccp_venture_capital' },
            { id = 'j_bccp_yay_all_7s' },

            -- no photochad for you 
            { id = 'j_photograph' },

        }
    }    
}